apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: registry.local:4000/accounts:0.0.3
          ports:
          - containerPort: 7072
          resources:
            limits:
              memory: "200Mi"
              #cpu: "5"
            requests:
              memory: "100Mi"
              #cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  type: ClusterIP
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 7072