apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: registry.local:4000/inventory:0.0.1
          ports:
          - containerPort: 7074
          resources:
            limits:
              memory: "200Mi"
              #cpu: "100"
            requests:
              memory: "100Mi"
              #cpu: "50"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 7074
      targetPort: 7074