# Packages stage
FROM node:14-alpine as packages

# Create root application folder
WORKDIR /app

# Copy configs to /app folder
COPY package*.json ./

# Copy source code to /app/src folder
COPY src /app/src

# Installing packages
RUN npm install

# Build stage
FROM packages

CMD [ "node", "./src/index.js" ]